### ISSUE TITLE
redirect to somewhere useful on login or registration

### ISSUE THREAD

**Issue by darrell** [pdxosgeo/foss4g2014-wordpress#10]
When creating an account, or logging in, is it possible to redirect users to some other page than the front page, so they can go right to submitting papers?

**Comment by mapsam** [comment]
Yup! You can set redirects in the "theme my login" settings in the wp-admin page. Since every user is a "subscriber" you only have to worry about that user-type redirect. Go to TML > Redirection > and scroll to the bottom you'll see the space to change the redirect URL.

![screen shot 2014-02-10 at 10 34 28 am](https://f.cloud.github.com/assets/1943001/2128998/021c6fdc-9282-11e3-954d-88bafaea826d.png)

**Comment by elil** [comment]
For login I changed it to referrer to let them continue on.  Does that seem correct?  Should work for the arrive at submission page --> login --> back to submission page.  This would not work for arrive at submission page --> register for account ---> login --> back to register for account?

**Comment by darrell** [comment]
works for me.
