### ISSUE TITLE
hide WP user frontend pro from repo

### ISSUE THREAD

**Issue by mapsam** [pdxosgeo/foss4g2014-wordpress#20]
Because it ain't free!

**Comment by mapsam** [comment]
Wait a second, since we've already staged in master, will we have to `git rm /../..` ? How will that affect the live version @darrell ?

**Comment by darrell** [comment]
I think it's ok for the source to be there as it has to have a license key
to work.

If you remove it, it will vanish from the production server, so we don't
want to push that.

d.

Am Feb 24, 2014 um 19:14 schrieb Sam Matthews notifications@github.com:

Wait a second, since we've already staged in master, will we have to git rm
/../.. ? How will that affect the live version
@darrellhttps://github.com/darrell?

## 

Reply to this email directly or view it on
GitHubhttps://github.com/pdxosgeo/foss4g2014-wordpress/issues/20#issuecomment-35970756
.

**Comment by darrell** [comment]
If we want to be anal, we can make sure it’s installed some other way.

**Comment by mapsam** [comment]
Ah, good call. Well let's just leave it as is then!
